# Generated by Django 4.1.7 on 2023-03-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_in_popular_products',
            field=models.BooleanField(default=False),
        ),
    ]
