# Generated by Django 4.1.7 on 2023-02-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='division',
        ),
        migrations.RemoveField(
            model_name='order',
            name='area',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='division',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
